### ISSUE TITLE
Examples are broken

### ISSUE THREAD

**Issue by janhohenheim** [BlackPhlox/bevy_dolly#21]
Getting the following when running `fpv` on `main`:
![image](https://user-images.githubusercontent.com/9047632/221722655-6e787526-e299-4a97-bec1-354a2d3ff10e.png)

The other examples report similar errors.

**Comment by BlackPhlox** [comment]
Thanks for notifying me! for some reason it didn't fail when I build on the previous push, might be me forgetting to do `cargo update`. I'll set up [trybuild](https://crates.io/crates/trybuild) for the examples next time so they can be caught in test phase of the CI

**Comment by janhohenheim** [comment]
Thanks for the fix! 😄
