### ISSUE TITLE
Update to Bevy 0.13

### ISSUE THREAD

**Issue by chambers** [BlackPhlox/bevy_dolly#54]
Please update your dependencies as glam types are conflicting with bevy e.g. Vec3. This is required to update the Foxtrot template to 0.13.

edit: I see @rparrett has already worked on this in #51

**Comment by janhohenheim** [comment]
@chambers I made an own branch and linked it in Foxtrot in the meantime, which is on Bevy v0.13 now :)

**Comment by BlackPhlox** [comment]
Thanks for the heads up guys, the crate is now updated to support Bevy 0.13:
https://github.com/BlackPhlox/bevy_dolly/releases/tag/0.0.3
