### ISSUE TITLE
Rust Analyzer tells me there is a Component in this crate named "Player" and this is really annoying.. if so, please rename

### ISSUE THREAD

**Issue by ethereumdegen** [BlackPhlox/bevy_dolly#57]
Rust Analyzer tells me there is a Component in this crate named "Player" and this is really annoying.. if so, please rename it to "DollyCameraPlayer" or something please.  It will only cause  drama related to conflicts/ collisions for new devs

**Comment by BlackPhlox** [comment]
This is now changed for bevy_dolly 0.0.4
