### ISSUE TITLE
Needs update to 0.14 

### ISSUE THREAD

**Issue by ethereumdegen** [BlackPhlox/bevy_dolly#59]
Hello, I use this crate for my bevy game and this is the final blocker to my being able to update to 0.14

**Comment by rparrett** [comment]
`bevy_dolly` users can use my PR as git dependency until @BlackPhlox finds time to look over the update and do a release.

```
bevy_dolly = { git = "https://github.com/rparrett/bevy_dolly", branch = "bevy-0.14" }
```

**Comment by BlackPhlox** [comment]
@ethereumdegen bevy_dolly is now updated to version 0.0.4 to support bevy 0.14
